# Generated by Django 5.2.8 on 2025-12-04 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ser nesse formato: XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$')], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve ser nesse formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve ser nesse formato: XXXXX-XXX', regex='^\\d{5}\\-\\d{3}$')], verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve ser nesse formato: XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}\\-\\d{2}$')], verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve ser nesse formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve ser nesse formato: XXXXX-XXX', regex='^\\d{5}\\-\\d{3}$')], verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Placa deve ser nesse formato: XXX-0000 ou ABC1D23', regex='^(?:[A-Z]{3}\\-\\d{4}|[A-Z]{3}\\d[A-Z]\\d{2})$')], verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('preco_base_dia', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Preço Base por Dia')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'db_table': 'carros',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuário')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ser nesse formato: XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$')], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve ser nesse formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Telefone')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(verbose_name='Data de Aluguel')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de Devolução Prevista')),
                ('data_devolucao_real', models.DateField(blank=True, null=True, verbose_name='Data de Devolução Real')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('carro', models.ForeignKey(db_column='carro_id', on_delete=django.db.models.deletion.CASCADE, to='core.carro', verbose_name='Carro')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('vendedor', models.ForeignKey(db_column='vendedor_id', on_delete=django.db.models.deletion.CASCADE, to='core.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
                'db_table': 'alugueis',
            },
        ),
    ]
