# Generated by Django 5.2.8 on 2025-12-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
