# Generated by Django 5.2.8 on 2025-12-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='preco_base_dia',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Preço Base por Dia'),
        ),
    ]
