# Generated by Django 5.2.8 on 2025-12-04 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve ser nesse formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve ser nesse formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve ser nesse formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
