# Generated by Django 5.1.7 on 2026-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluguel_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='status_aluguel',
            field=models.CharField(choices=[('criado', 'Criado'), ('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('com_atraso', 'Com Atraso'), ('cancelado', 'Cancelado')], default='criado', max_length=20, verbose_name='Status do Aluguel'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='aplica_acrescimo_feriado',
            field=models.BooleanField(default=True, verbose_name='Acréscimo em Feriados (20%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='aplica_acrescimo_fim_semana',
            field=models.BooleanField(default=False, verbose_name='Acréscimo em Fim de Semana (15%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='aplica_acrescimo_temporada_alta',
            field=models.BooleanField(default=False, verbose_name='Acréscimo Temporada Alta (25%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_calculo',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('premium', 'Premium'), ('comercial', 'Comercial')], default='padrao', max_length=20, verbose_name='Tipo de Cálculo de Aluguel'),
        ),
    ]
